export const ALGERIA_WILAYAS_COMMUNES: Record<string, string[]> = {
  "Adrar": [
    "Adrar", "Tamest", "Charouine", "Reggane", "In Zghmir", "Tit", "Ksar Kaddour",
    "Tsabit", "Tamentit", "Fenoughil", "Tinerkouk", "Zaouiet Kounta", "Aoulef",
    "Timokten", "Akabli", "Metarfa", "Ouled Said", "Sali", "Ouled Ahmed Timmi",
    "Bouda", "Aougrout", "Talmine", "Deldoul", "Sbaa", "Ouled Aissa",
  ],
  "Chlef": [
    "Chlef", "Ténès", "Benairia", "El Karimia", "Taougrite", "Beni Haoua", "Sobha",
    "Harchoun", "Ouled Fares", "Sidi Akkacha", "Boukadir", "Beni Rached", "Talassa",
    "Labiod Medjadja", "El Marsa", "Oued Goussine", "Dahra", "Ouled Abbes", "Sendjas",
    "Zeboudja", "Breira", "Ain Merane", "Ouled Sidi Abdelkader", "Chettia",
    "Sidi Abderrahmane", "Moussadek", "El Hadjadj", "Herenfa", "Oum Drou",
    "Beni Bouattab", "El Ghernainia", "Bouzghaia", "Abou El Hassan",
  ],
  "Laghouat": [
    "Laghouat", "Ksar El Hirane", "Bennacer Benchohra", "Sidi Makhlouf", "Hassi Delaa",
    "Hassi R'Mel", "Ain Mahdi", "Tadjemout", "Kheneg", "Gueltet Sidi Saad",
    "Ain Sidi Ali", "Beidha", "Brida", "El Ghicha", "Hadj Mechri", "Sebgag",
    "Taouiala", "Tadjrouna", "Aflou", "El Haouaita", "Oued Morra", "Oued M'zi",
    "El Assafia", "Sidi Bouzid",
  ],
  "Oum El Bouaghi": [
    "Oum El Bouaghi", "Ain Beida", "Ain M'lila", "Ain Fakroun", "Ksar Sbahi",
    "Ain Kercha", "Hanchir Toumghani", "Berriche", "El Amiria", "Souk Naamane",
    "Zorg", "El Fedjoudj", "Bir Chouhada", "Oued Nini", "Fkirina", "Ain Babouche",
    "Rahia", "Bir Lahlou", "Sif Lokba", "Sigus", "El Djazia", "Ain Zitoun",
    "Ouled Zouai", "Dhalaa", "Ain Diss", "Ouled Hamla", "Ain Kercha", "Meskiana",
  ],
  "Batna": [
    "Batna", "Ain Touta", "Arris", "N'Gaous", "Barika", "El Madher", "Merouana",
    "Seriana", "Ghassira", "Inoughissen", "Ouled Si Slimane", "Ghoufi", "Ain Djasser",
    "Ouled Aouf", "Boulhilat", "Lazrou", "Boumagueur", "Boulhilat", "Ksar Bellezma",
    "Seggana", "Ichmoul", "Taxlent", "Boumia", "Menaa", "Rhoufi", "Ain Yagout",
    "Fesdis", "Tighanimine", "Larbaa", "Djerma", "Maafa", "Ouled Fadel",
    "Rahbat", "Tilatou", "Ain Skhouna", "Ouyoun El Assafir", "Djerma",
    "Hidoussa", "Guergarif", "Tizi N'Bechar", "Chir", "Lemsane",
    "El Hassi", "Ouled Sellam", "Metallaoui", "Abdelkader Azil", "Sefiane",
    "Ain Touta", "Tighanimine", "Boulhilat",
  ],
  "Béjaïa": [
    "Béjaïa", "Akbou", "Souk El Tenine", "Tichy", "El Kseur", "Amizour",
    "Fenaia Ilmaten", "Taourirt Ighil", "Chemini", "Seddouk", "Tazmalt",
    "Ighil Ali", "Feraoun", "Tifra", "Adekar", "Amalou", "Ighram",
    "Aouzellaguen", "Bouhamza", "Beni Djellil", "Leflaye", "Kherrata",
    "Draa El Gaid", "Beni Maouche", "Aokas", "Bejaia", "Toudja", "Oued Ghir",
    "Boukhelifa", "Tala Hamza", "Ferraoun", "Melbou", "Ziama Mansouriah",
    "Kendira", "Beni K'sila", "Souk Oufella", "Tibane", "Tamokra",
    "Darguina", "Sidi Ayad", "Akfadou", "Beni Ksila", "Taskeriout",
    "El Flaye", "Beni Mellikeche", "Ait R'Zine", "Agrioun", "Imsouhal",
    "Sidi Aich", "Barbacha", "Kendira", "Kherrata",
  ],
  "Biskra": [
    "Biskra", "Tolga", "Ourlal", "Sidi Okba", "Djemorah", "El Kantara",
    "Ain Naga", "Zeribet El Oued", "El Hadjeb", "Branis", "Chetma", "Lioua",
    "Lichana", "Oumache", "Foughala", "Bordj Ben Azzouz", "M'Chouneche",
    "El Feidh", "Bouchagroun", "Mekhadma", "Ain Zaatout", "Besbes",
    "Khangat Sidi Nadji", "El Ghrous", "Meziraa", "Doucen",
    "Ras El Miad", "Sidi Khaled", "Ouled Djellal (Biskra)",
  ],
  "Béchar": [
    "Béchar", "Kenadsa", "Lahmar", "Beni Abbes", "Erg Ferradj", "El Ateuf",
    "Boukais", "Ouled Khoudir", "Meridja", "Igli", "Timoudi", "Abadla",
    "Kerzaz", "Tamtert", "Mechraa Houari Boumediene", "Taghit", "Beni Ikhlef",
    "Mogheul", "Oulad Khodeir", "El Ouata", "Tabelbala", "Tinerkouk",
  ],
  "Blida": [
    "Blida", "Boufarik", "Larbaâ", "Larbaa", "Mouzaia", "El Affroun",
    "Chréa", "Oued El Alleug", "Oued Djer", "Soumaa", "Beni Tamou",
    "Bouarfa", "Ain Romana", "Chiffa", "Hammam Melouane", "Meftah",
    "Guerrouaou", "Benkhelil", "Ouled Selama", "Souhane", "Bouinan",
    "Bougara", "Cherif El Idrissi", "Larbaa", "Ben Khelil",
  ],
  "Bouira": [
    "Bouira", "Lakhdaria", "M'Chedallah", "Sour El Ghouzlane", "Ain Bessem",
    "El Asnam", "Ain El Hadjar", "Bechloul", "El Hachimia", "Dirah",
    "Haizer", "Kadiria", "Zbarbar", "Taghzout", "El Adjiba", "Bordj Okhriss",
    "El Mokrani", "Chorfa", "Ain Laloui", "Ahl El Ksar", "El Khabouzia",
    "Ath Mansour", "Maala", "Ridane", "Aomar", "Dechmia",
    "Taghzout", "Aghbalou", "Guerrouma", "Oued El Berdi", "Bouderbala",
    "Bir Ghbalou", "Saharidj", "Raffour", "Maalou", "Aghbalou N'kerdache",
    "Ouled Rached", "Souk El Khemis", "Aïn El Turc", "Boukram",
    "Hadjra Zerga", "Taguedite", "Timezrit",
  ],
  "Tamanrasset": [
    "Tamanrasset", "Abalessa", "In Ghar", "In Guezzam", "Idles", "Tazrouk",
    "Tin Zaouatine", "Foggaret Ez Zoua", "In Salah", "Silet", "Ain Amguel",
  ],
  "Tébessa": [
    "Tébessa", "Bir El Ater", "Cheria", "Ain Zerga", "Ouenza", "El Meriig",
    "Bir Mokadem", "Bekkaria", "El Ogla", "Negrine", "El Ogla El Malha",
    "Bir El Ater", "Stah Guentis", "El Aouinet", "El Kouif", "Thlidjene",
    "Bir Dheb", "Safsaf El Ouesra", "El Houidjbet", "Boukhadra",
    "Hammamet", "Ferkane", "Djebet Betroun",
  ],
  "Tlemcen": [
    "Tlemcen", "Maghnia", "Ghazaouet", "Sebdou", "Bensekrane", "Hennaya",
    "Ain Tallout", "Remchi", "El Fehoul", "Sabra", "Sidi Abdelli",
    "Azail", "Ain Fezza", "Ouled Mimoun", "Ain Ghoraba", "Chetouane",
    "El Boukhari", "Sebbaa Chioukh", "Sidi Djillali", "Boukhanafis",
    "El Gor", "Sebra", "Marsa Ben M'hidi", "Nedroma", "Souahlia",
    "Msirda Fouaga", "Ain Kebira", "Bab El Assa", "Dar Yaghmoracen",
    "Fellaoucene", "Hammam Boughrara", "Mansourah", "Honaine", "Beni Snous",
    "Beni Boussaid", "Ain Youcef", "El Aricha", "Sidi Medjahed",
    "Ain Fetah", "Hammam Boughrara", "Sidi Ouarsous",
    "Tienet", "Terny Beni Hdiel", "Souk Tlata", "Ain Tallout",
  ],
  "Tiaret": [
    "Tiaret", "Ksar Chellala", "Sougueur", "Mehdia", "Ain Dheb",
    "Frenda", "Mahdia", "Ain Kermes", "Hamadia", "Rahouia",
    "Oued Lilli", "Medrissa", "Bougara", "Sebaine", "Takhemaret",
    "Ain El Hadid", "Ouled Djerad", "Nadorah", "Guertoufa", "Sidi Bakhti",
    "Ain Zarit", "Beni Iloul", "Tagdemt", "Rechaiga", "Naima",
    "Zaaroura", "Sidi Ali Mellal", "Mechraa Safa", "Dahmouni",
    "Ain El Hadid", "Oued Tolba", "Chehaima", "Sebaïne", "Serghine",
    "Wadi El Abtal", "Zmalet El Emir Abdelkader", "Medjedel", "Sehailia",
    "Tirekhine", "Tousnina", "Meghila",
  ],
  "Tizi Ouzou": [
    "Tizi Ouzou", "Azazga", "Ain El Hammam", "Draâ El Mizan", "Tigzirt",
    "Draa Ben Khedda", "Boghni", "Beni Yenni", "Ouadhia", "Ifigha",
    "Ouaguenoun", "Azeffoun", "Makouda", "Freha", "Bouzeguene",
    "Maatkas", "Sidi Naamane", "Ait Agouacha", "Illilten", "Beni Zmenzer",
    "Iferhounene", "Tizi Gheniff", "Aghribs", "Imsouhal", "Irdjen",
    "Bounouh", "Ain Zaouia", "Mkira", "Ait Mahmoud", "Beni Aissi",
    "Ath Douala", "Souk El Tenine", "Tizi Rached", "Ouled Aissa",
    "Yatafen", "Illoula Oumalou", "Mechtras", "Idjeur", "Ait Oumalou",
    "Iboudraren", "Akerrou", "Aït Aggouacha", "Tirmitine", "Souamaa",
    "Boghni", "Beni Yenni", "Larbaa Nath Irathen", "Ait Yahia",
    "Ait Yahia Moussa", "Aghribs", "Tadmait", "Ifigha", "Bouzeguene",
    "Ouadhia", "Tizi Rached", "Beni Douala", "Mkira", "Aïn El Hammam",
    "Irdjen", "Yakourene", "Frikat", "Azzefoun", "Tigzirt",
    "Mekla", "Tizi N'Tleta", "Timizart",
  ],
  "Alger": [
    "Alger-Centre", "Sidi M'Hamed", "El Madania", "Belouizdad", "Bab El Oued",
    "Bologhine Ibn Ziri", "Casbah", "Oued Koriche", "Birmandreis", "El Harrach",
    "Baraki", "Oued Smar", "Bachdjerrah", "Hussein Dey", "Kouba", "Bourouba",
    "Dar El Beïda", "Bab Ezzouar", "Ben Aknoun", "Dely Ibrahim", "El Biar",
    "Bouzareah", "Birkhadem", "Hydra", "Mohammadia", "Bordj El Bahri", "El Marsa",
    "Rouïba", "Réghaia", "Ain Taya", "Bordj El Kiffan", "El Magharia",
    "Ain Benian", "Staoueli", "Zeralda", "Mahelma", "Rahmania", "Souidania",
    "Cheraga", "Ouled Fayet", "El Achour", "Draria", "Douera", "Baba Hassen",
    "Khraichia", "Saoula", "Eucalyptus", "Birtouta", "Tessala El Merdja",
    "Sidi Moussa", "Fondouk", "Hammamet", "Ain de Mel", "El Hammamet",
    "Les Eucalyptus", "Ain Taya",
  ],
  "Djelfa": [
    "Djelfa", "Messaad", "Ain Oussera", "Moudjbara", "El Idrissia", "Charef",
    "Zakar", "Birine", "Selmana", "Ain Fekka", "Sed Rahal", "Faidh El Botma",
    "Douis", "Hassi Bahbah", "Ain Maabed", "Sed Rahal", "El Guedid",
    "Had Sahary", "Guernini", "Sidi Baizid", "Deldoul", "Ain Chouhada",
    "Ouled Nail", "Ould Nail", "Dar Chioukh", "Amourah", "Benhar",
    "El Khemis", "Zaccar", "Bouira Lahdab", "Ain El Ibel", "Ain Oussera",
    "Oum Laadham", "Hassi El Euch", "Mliliha",
  ],
  "Jijel": [
    "Jijel", "El Milia", "Taher", "Chekfa", "El Aouana", "Ziama Mansouriah",
    "Selma Ben Ziada", "Djimla", "Ghebala", "Bouraoui Belhadef", "Kaous",
    "Boudria Beni Yadjis", "Beni Yadjis", "Emir Abdelkader", "Texenna",
    "Sidi Maarouf", "Settara", "El Ancer", "Oudjana", "Chahna",
    "Ain Makhlouf", "Ain Soltane", "Bordj T'Har", "Erraguene",
    "Djimla", "Sidi Abdelaziz", "Valmy",
  ],
  "Sétif": [
    "Sétif", "El Eulma", "Ain Oulmene", "Bougaa", "Ain Arnat", "Ain Azel",
    "Guenzet", "Bir Haddad", "El Ouricia", "Djemila", "Amoucha", "Babor",
    "Beni Ourtilane", "Maoklane", "Ksar El Abtal", "Bir El Arch",
    "Ouled Tebben", "Hamma", "Dehamcha", "Tachouda", "El Bez",
    "Ait Naoual Mezada", "Ain Lahdjar", "Ain Legraj", "Guedjel",
    "Mezloug", "Bougaa", "Ouled Adouane", "El Ouldja", "Guidjel",
    "Rosfa", "Tizi N'Bechar", "Tizi Ghenaif", "Draâ Kebila",
    "Hammam Guergour", "Hammam Soukhna", "Maoklane", "Ain Abessa",
    "Beni Mouhli", "Ouled Saber", "Djellal", "Ain Roua", "Aïn Sebt",
    "Boutaleb", "Ain Oulmene", "Sétif centre",
  ],
  "Saïda": [
    "Saïda", "Ain El Hadjar", "Youb", "Moulay Larbi", "Doui Thabet",
    "Ain Skhouna", "Ouled Brahim", "Sidi Amar", "Hassasna", "Tircine",
    "Hounet", "Ouled Khaled", "Ain Soltane", "Maamora", "El Hassasna",
    "El Bradia",
  ],
  "Skikda": [
    "Skikda", "El Harrouch", "Ain Cherchar", "Collo", "Tamalous",
    "Zitouna", "El Hadaiek", "Beni Bechir", "Oum Toub", "Hamadi Krouma",
    "El Marsa", "Salah Bouchaour", "Kerkera", "Bouchtata", "Ouldja Boulbalout",
    "Beni Zid", "Djendel Saadi Mohamed", "Emdjez Edchich", "Filfila",
    "Azzaba", "Ain Zouit", "Bejou", "Ramdan Djamel", "Ain Bouziane",
    "Ramdane Djamel", "Ain Kechra", "Zerdazas", "Sidi Mezghiche",
    "Ain Cherchar", "Oued Zehour", "Beni Oulbane", "El Hadaiek",
    "Ain Charef", "Oum Toub", "Ouled Attia", "Cheraia",
  ],
  "Sidi Bel Abbès": [
    "Sidi Bel Abbès", "Telagh", "Ras El Ma", "Mostefa Ben Brahim",
    "Sidi Hamadouche", "Tessala", "Ain Thrid", "Lamtar", "Zero",
    "Mezaourou", "Merine", "Benachiba Chelia", "Hassi Zahana",
    "Ain Kada", "Ben Badis", "El Hacaiba", "Ain El Berd", "Sidi Chaib",
    "Tafissour", "Amarnas", "Sidi Ali Boussidi", "Sidi Ali Benyoub",
    "Marhoum", "Tenira", "Boudjebha El Bordj", "Bir El Hammam",
    "Sfisef", "Maamria", "Makedra", "Redjem Demouche", "Tabia",
    "Oued Sebbah", "Oued Taimat", "Sendjas",
  ],
  "Annaba": [
    "Annaba", "El Bouni", "El Hadjar", "Ain Berda", "Chetaibi",
    "Seraidi", "Treat", "Oued El Aneb", "Chorfa", "Berrahal",
    "Eulma", "Cheurfa",
  ],
  "Guelma": [
    "Guelma", "Bouchegouf", "Ain Makhlouf", "Ain Ben Beida", "Ain Sandel",
    "Héliopolis", "Houari Boumediene", "Khezaras", "Medjez Amar",
    "Medjez Sfa", "Nechmeya", "Oued Zenati", "Tamlouka", "Bendjerrah",
    "Bouhachana", "Bouhamdane", "El Fedjoudj", "El Fidja", "Hammam Debagh",
    "Hammam N'Bails", "Khimeunissa", "Ras El Agba", "Sellaoua Announa",
    "Taya", "Ain Herodj", "Ain Larbi", "Oued Fragha", "Belkheir",
    "Djebala", "Bouati Mahmoud", "Guelaât Bou Sbaâ",
  ],
  "Constantine": [
    "Constantine", "El Khroub", "Ain Abid", "Beni Hamidane", "Ibn Ziad",
    "Zighoud Youcef", "Hamma Bouziane", "Ain Smara", "Messaoud Boudjeriou",
    "Ouled Rahmoune", "Didouche Mourad",
  ],
  "Médéa": [
    "Médéa", "Berrouaghia", "Ksar El Boukhari", "Tablat", "Ouled Antar",
    "El Omaria", "Ain Boucif", "El Azizia", "Beni Slimane", "Chahbounia",
    "Medjez Sidi Aissa", "Boghari", "Ouamri", "Sedraia", "El Guelb El Kebir",
    "Sidi Damed", "Si Mahdjoub", "Tafraout", "Meftah", "Benchicao",
    "Mihoub", "Saneg", "Oued Harbil", "Aziz", "Ain Ouksir",
    "Rebaia", "Djouab", "Ouzera", "Ain El Ksiba", "El Hamdania",
    "Ouled Maaref", "Cheniguel", "Ain Ouksir", "Sidi Naamane",
    "Beni Rached", "El Kesbat", "Derrag", "Gourbissa", "El Omaria",
    "Sidi Ziane", "Si Mahdjoub", "Oued Harbil", "Sidi Damed",
    "Sidi Ali Lebher", "Souaghi", "Mezerena", "Afir", "Tamesguida",
    "Ouled Hellal", "Seghouane", "Bou Aiche", "Ain Ouksir",
    "Ain Boucif", "Tablat",
  ],
  "Mostaganem": [
    "Mostaganem", "Ain Tedeles", "Sidi Ali", "Achacha", "Hadjadj",
    "Mesra", "Khadra", "Bouguirat", "Tazgait", "Ain Nouissy",
    "Ain Boudinar", "Ain Sidi Cherif", "Sirat", "Ouled Maallah",
    "Ain Tedles", "Ain Sidi Cherif", "El Haciane", "Kheir Eddine",
    "Stidia", "Mazagran", "Fornaka", "Nekmaria", "Oued El Kheir",
    "Safsaf", "Mansourah", "Oued El Kheir", "Sidi Belattar",
    "Abdelmalek Ramdane", "Benabdelmalek Ramdane", "Ain Sidi Cherif",
    "Achaacha", "Touahria",
  ],
  "M'Sila": [
    "M'Sila", "Bou Saada", "Ain El Melh", "Sidi Aissa", "Ouled Derradj",
    "Magra", "Djezzar", "Ain El Hadjel", "Hammam Dalaa", "Ben Srour",
    "El Houamed", "Ouanougha", "Khoubana", "Chellal", "Ain Fares",
    "Bou Saada", "Medjedel", "Maadid", "El Hamel", "El Mansourah",
    "Sidi Ameur", "Dehahna", "Ain Errich", "Oued Chaaba",
    "Metarfa", "Ain Khadra", "Ben Zouh", "Berhoum", "El Assa",
    "Ouled Atia", "Maarif", "Slim", "Hammam Dalaa", "Sidi Ameur",
    "Ain Errich", "Maadid", "Sidi M'Hamed",
  ],
  "Mascara": [
    "Mascara", "Sig", "El Bordj", "Tighennif", "Mohammadia", "Ain Fekan",
    "Bou Hanifia", "Oued El Abtal", "El Keurt", "Froha", "Matemore",
    "Ain Fares", "Khalouia", "Maoussa", "Sidi Kada", "Ferraguig",
    "Nesmoth", "El Ghomri", "Sedjerara", "Gharrous", "Ain Fekan",
    "Ghriss", "Hachem", "Zelmata", "Beniane", "Oggaz",
    "Alaimia", "Sidi Boussaid", "Ain Frass", "Ain Fekan",
    "El Bordjia", "Guerdjoum", "Ain Fekan", "Oued Taria",
    "Bou Hanifia", "Hacine", "Sidi Abdelmoumen", "El Faiçal",
    "Ras Ain Amirouche", "Ain Frass", "Ain Itim",
  ],
  "Ouargla": [
    "Ouargla", "Hassi Messaoud", "El Hadjira", "Touggourt", "Temacine",
    "Ain Beida", "El Borma", "Rouissat", "Sidi Khouiled", "Tebesbest",
    "N'Goussa", "Zaouia El Abidia", "Hassi Ben Abdallah", "Ben Nasser",
    "El Allia", "Nezla", "Taibet",
  ],
  "Oran": [
    "Oran", "Es Senia", "Bir El Djir", "Hassi Bounif", "Arzew",
    "Bethioua", "Marsat El Hadjadj", "Ain El Turk", "El Ancor",
    "Oued Tlelat", "Tafraoui", "Sidi Chahmi", "El Kerma", "Misserghine",
    "Ben Freha", "Messerghin", "Bousfer", "Ain El Kerma", "Ain Biya",
    "El Braya", "Senia", "Sidi Marouf", "Ain El Bia", "Bougnoun",
    "Boufatis", "Hassi Mefsoukh",
  ],
  "El Bayadh": [
    "El Bayadh", "Rogassa", "Brezina", "Ghassoul", "Ain El Orak",
    "Chellala", "Sidi Ameur", "Boualem", "El Aouedj", "Lahmar",
    "Krakda", "Arbaouat", "Ain Oussera", "Bougtob", "Sidi Slimane",
    "El Bnoud", "Touama", "Sidi Tifour", "Tiout", "Mehara", "Stitten",
  ],
  "Illizi": [
    "Illizi", "Djanet", "In Amenas", "In Guezzam", "Debdeb", "Bordj Omar Driss",
  ],
  "Bordj Bou Arréridj": [
    "Bordj Bou Arréridj", "El Achir", "Ras El Oued", "Bordj Zemoura",
    "Mansourah", "Medjana", "Tixter", "Colla", "Khelil",
    "Bir Kasdali", "El Hamadia", "Djaafra", "Ouled Sidi Brahim",
    "Hasnaoua", "El Ach", "Aïn Taghrout", "Ouled Brahem", "Rabta",
    "Ghilassa", "Taglait", "Sidi Embarek", "Teniet En Nasr",
    "Belimour", "Tesmart", "El Main", "Ain Tesra", "Teniet En Nasr",
    "Ouled Dahmane", "Ridane", "Elkohol", "Zemmora",
  ],
  "Boumerdès": [
    "Boumerdès", "Bordj Menaiel", "Khemis El Khechna", "Boudouaou",
    "Naciria", "Isser", "Thenia", "Corso", "Si Mustapha", "Dellys",
    "Zemmouri", "Ouled Moussa", "Beni Amrane", "Chabet El Ameur",
    "Tidjelabine", "Leghata", "Larbatache", "Sidi Daoud", "Boudouaou El Bahri",
    "Hammedi", "Ain Taya", "Ammal", "Baghlia", "Afir",
    "Souk El Had", "Ben Choud", "Ouled Haddadj", "Kirou",
    "Sidi Naamane", "Djinet", "El Kharrouba",
  ],
  "El Tarf": [
    "El Tarf", "El Kala", "Ben M'hidi", "Bouteldja", "Besbes",
    "Bougous", "Ain El Assel", "Chihani", "Berrihane", "Ain Kerma",
    "Zerizer", "Lac Des Oiseaux", "Souarekh", "Dréan", "Chbaita Mokhtar",
    "Raml Souk", "Hamam Beni Salah", "Oued Zitoun", "El Aioun", "Echatt",
    "Zitouna", "Ain Assel",
  ],
  "Tindouf": [
    "Tindouf", "Oubeïra", "Oum El Assel", "Samara",
  ],
  "Tissemsilt": [
    "Tissemsilt", "Khemisti", "Ain Bouchekif", "Sidi Slimane", "Sidi Abed",
    "Ouled Bessem", "Bordj Bou Naama", "Beni Chaib", "Ammari", "Lazharia",
    "Theniet El Had", "Layoune", "Melaab", "Boucaid", "Larbaâ",
    "Sidi Boutouchent", "Beni Lahcene", "Yousef Ben Khedda", "Maacem",
    "El Bord", "Ain Dzarit", "Bordj El Emir Abdelkader",
  ],
  "El Oued": [
    "El Oued", "Robbah", "Oued El Alenda", "Bayadha", "Nakhla",
    "Guemar", "Kouinine", "Reguiba", "Hamraia", "Taghzout",
    "Debila", "Hassani Abdelkrim", "Hadjira", "Still", "Trifaoui",
    "Magrane", "Beni Guecha", "Ourmas", "Ain El Beida", "Trifaoui",
    "Oum Touyour", "Sidi Aoun", "Mih Ouansa", "Tendla", "Douar El Ma",
    "Mrara", "Sidi Khellil", "El Ogla", "Sidi Salem", "El M'Ghair",
  ],
  "Khenchela": [
    "Khenchela", "Kais", "Chechar", "El Mahmel", "Djellal",
    "Ain Touila", "Taouzianat", "Ensigha", "El Hamma", "Yabous",
    "Bouhmama", "M'Sara", "Khirane", "Remila", "Tamza",
    "Babar", "Bamendil", "El Oueldja", "Khaled",
  ],
  "Souk Ahras": [
    "Souk Ahras", "Sedrata", "Hanancha", "Mechroha", "Bir Bouhouche",
    "Oum El Adhaim", "Taoura", "Ain Soltane", "Safel El Ouidane",
    "Tiffech", "Ain Zana", "Ain Zitoun", "Merahna", "Ouled Moumen",
    "Terraguelt", "Drea", "Khemissa", "Zaarouria", "Sidi Fredj",
    "Oued Keberit", "Oued Moumen", "Rahia", "Ain Yadel",
  ],
  "Tipaza": [
    "Tipaza", "Kolea", "Cherchell", "Hadjout", "Ain Tagourait",
    "Mazouna", "Sidi Semiane", "Menaceur", "Larhat", "Damous",
    "Meurad", "Chaiba", "Aghbal", "Sidi Ghiles", "Messelmoun",
    "Ain Benian", "Bou Ismail", "Fouka", "Beni Milleuk", "Nador",
    "El Achouat", "Douaouda", "Hadjout", "Gouraya", "Oued El Alleug",
    "Ahmar El Ain", "Bouharoun",
  ],
  "Mila": [
    "Mila", "Chelghoum Laid", "Ferdjioua", "Tadjenanet", "Ain Beida Harriche",
    "El Ayadi Barbes", "Hamala", "Grarem Gouga", "Benyahia Abderrahmane",
    "Sidi Khelifa", "Ahmed Rachedi", "Teleghma", "El Mechira",
    "Bouhatem", "Ain Tine", "El Ouahchi", "Ain Mlouk",
    "Zeghaia", "Oued Seguen", "Terrai Bainen", "Tiberguent",
    "Oued Endja", "Sidi Merouane", "Rouached", "Ain El Beida",
  ],
  "Aïn Defla": [
    "Aïn Defla", "Khemis Miliana", "El Abadia", "Miliana", "Rouina",
    "Mekhatria", "Djendel", "El Amra", "El Attaf", "Ain Lechiakh",
    "Arib", "Bir Ould Khelifa", "Hammam Righa", "Bourached",
    "Oued Chorfa", "Ain Soltane", "Ain Torki", "Hoceinia",
    "Belaas", "Tacheta Zougagha", "Djeddar", "Ain Benali Messaoud",
    "Sidi Lakhdar", "Tiberkanine", "Bathia", "El Hassania",
    "Oued El Djemaa", "Boumedfaa", "Barbouche", "Bir Ould Khelifa",
    "Tacheta Zougagha", "Ain Benali Messaoud", "Sidi Lakhdar", "Boumedfaa",
    "Oued Djemaa",
  ],
  "Naâma": [
    "Naâma", "Mecheria", "Ain Sefra", "Tiout", "Sfissifa", "Moghrar",
    "El Biod", "Kasdir", "Djenien Bourezg", "Makman Ben Amer",
    "Ain Ben Khellil", "Ain El Orak",
  ],
  "Aïn Témouchent": [
    "Aïn Témouchent", "Hammam Bou Hadjar", "El Amria", "Beni Saf",
    "Ain Kihal", "El Malah", "El Emir Abdelkader", "Aghlal",
    "Ouled Kihal", "Ain Tolba", "Aoubellil", "Sidi Safi",
    "Terga", "Oulhaça El Gheraba", "Ain El Arbaa", "Oued Berkeche",
    "Sidi Ben Adda", "Mezaourou", "Souk El Sebt", "Ain Lerkam",
    "Chentouf", "Ghazaouet", "Hassasna", "Bou Zedjar",
    "Ain El Assel", "Tamzoura", "Oued Sabah",
  ],
  "Ghardaïa": [
    "Ghardaïa", "El Guerrara", "Berriane", "El Atteuf", "Bounoura",
    "Zelfana", "El Menea", "Dhayet Ben Dhahoua", "Metlili",
    "Mansoura", "Sebseb", "Hassi El Fehal", "Hassi Gara",
  ],
  "Relizane": [
    "Relizane", "Mazouna", "Zemmoura", "Oued Rhiou", "Sidi M'Hamed",
    "Ain Rahma", "Ouled Sidi Mihoub", "Ramka", "El Hamadna",
    "Sidi Lazarek", "Yellel", "Lahmoudia", "Kalaa", "Ammi Moussa",
    "El Guettar", "Had Echkalla", "Oued El Djemaa", "Ain Tarek",
    "Bendaoud", "Zemmora", "Mendes", "Djidioua", "El Matmar",
    "El Ouldja", "Beni Tobeur", "Si Abdelghani", "Sidi Saada",
    "Kherba", "Dar Ben Abdellah", "Ouarizane", "Belassel Bouzegza",
    "Ain El Hamam", "Ouled Aiche", "Ouguenoun", "Hilil", "Bougroun",
    "Zerga",
  ],
  "Timimoun": [
    "Timimoun", "Aougrout", "Charouine", "Deldoul", "Metarfa",
    "Ouled Said", "Ouled Aissa", "Talmine", "Tsabit", "Ksar Kaddour",
  ],
  "Bordj Badji Mokhtar": [
    "Bordj Badji Mokhtar", "Timiaouine", "In Khalil", "Tinouker",
    "Awaday", "Anou Aghref",
  ],
  "Ouled Djellal": [
    "Ouled Djellal", "Doucen", "Sidi Khaled", "Ras El Miad",
    "Charef", "El Ghrous", "Ben Nacer", "Sidi Okba",
  ],
  "Béni Abbès": [
    "Béni Abbès", "Erg Ferradj", "El Ouata", "Igli", "Tabelbala",
    "Tamtert", "Kerzaz", "Timoudi", "El Bnoud",
  ],
  "In Salah": [
    "In Salah", "Foggaret Ez Zoua", "In Ghar", "Aoulef", "Silet", "Reggane",
  ],
  "In Guezzam": [
    "In Guezzam", "Tin Zaouatine", "Idles",
  ],
  "Touggourt": [
    "Touggourt", "Temacine", "Nezla", "Taibet", "Tebesbest",
    "Zaouia El Abidia", "El Hadjira", "Benaceur", "Megaliss",
    "El Allia", "Sidi Slimane", "Mnagueur", "Oued El Alenda", "Djamaa",
  ],
  "Djanet": [
    "Djanet", "Bordj Omar Driss",
  ],
  "El M'Ghair": [
    "El M'Ghair", "Djamaa", "Sidi Khellil", "Mrara", "Oum Touyour",
    "Still", "Tendla", "Sidi Aoun",
  ],
  "El Meniaa": [
    "El Meniaa", "Hassi Gara", "Sebseb", "Hassi El Fehal", "El Hadjira",
  ],
};

export const WILAYAS = Object.keys(ALGERIA_WILAYAS_COMMUNES);
